
# 2026.03.18 평가

# 차량 판매 정보 시스템

# 자동차정보 (CAR_INFO) –모델번호(PK), 모델명, 금액, 제조사
CREATE TABLE CAR_INFO (
	CAR_NUM INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, CAR_NAME VARCHAR(50) NOT NULL
	, CAR_PRICE INT NOT NULL
	, CAR_COMPANY VARCHAR(50) NOT NULL
);


#자동차판매정보(SALES_INFO) –판매번호(PK), 구매자명, 구매자연락처, 색상, 판매일, 모델번호(FK)
CREATE TABLE SALES_INFO (
	SALES_NUM INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, BUYER_NAME VARCHAR(20) NOT NULL
	, BUYER_CONTACT VARCHAR(50)
	, SALES_COLOR VARCHAR(50) NOT NULL
	, CAR_NUM INT NOT NULL REFERENCES CAR_INFO (CAR_NUM)
);

SELECT * FROM CAR_INFO ORDER BY CAR_NUM DESC;
SELECT * FROM SALES_INFO;

#테이블에 빠진 판매일추가
ALTER TABLE SALES_INFO ADD COLUMN SALES_DATE DATETIME DEFAULT CURRENT_TIMESTAMP;

DELETE FROM CAR_INFO;
DELETE FROM SALES_INFO;




